# Generated by Django 5.0.2 on 2024-04-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seller',
            new_name='viewer',
        ),
    ]
