# Generated by Django 5.0.2 on 2024-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0002_rename_seller_booking_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agent',
            field=models.CharField(max_length=100),
        ),
    ]
