# Generated by Django 5.0.2 on 2024-03-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agents', '0003_delete_agent'),
        ('authentication', '0004_rename_admin_userprofile_is_agent'),
        ('property', '0008_alter_commercialproperty_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='property.allproperty')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_seller', to='authentication.userprofile')),
            ],
        ),
    ]
