# Generated by Django 5.0.2 on 2024-04-02 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Name', models.CharField(max_length=200)),
                ('Property_Description', models.TextField(blank=True, null=True)),
                ('Total_area_in_sqft', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('Price', models.IntegerField(default=0)),
                ('Property_Pictures', models.ImageField(upload_to='pics')),
                ('Road_No', models.CharField(max_length=4)),
                ('Block', models.CharField(max_length=10)),
                ('City', models.CharField(choices=[('Dhaka', 'Dhaka')], max_length=100)),
                ('Postal_code', models.CharField(max_length=4)),
                ('Area', models.CharField(choices=[('Gulshan', 'Gulshan'), ('Banani', 'Banani'), ('Dhanmondi', 'Dhanmondi'), ('Bashundhara R/A', 'Bashundhara R/A')], max_length=100)),
                ('Property_on', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=20, null=True)),
                ('Property_type', models.CharField(choices=[('commercial', 'Commercial'), ('land', 'Land'), ('residential', 'Residential')], max_length=20)),
                ('Approval_by_Agent', models.CharField(max_length=50, null=True)),
                ('Property_Documents', models.FileField(upload_to='property_documents')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialProperty',
            fields=[
                ('allproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.allproperty')),
                ('House_No', models.CharField(max_length=8)),
                ('Business_type', models.CharField(choices=[('office', 'Office'), ('community_Center', 'community_Center'), ('shop', 'Shop'), ('other', 'Other')], max_length=20, null=True)),
                ('Parking_spaces', models.PositiveIntegerField(default=0)),
                ('Has_elevator', models.BooleanField(default=False)),
                ('Has_security_system', models.BooleanField(default=False)),
                ('Has_conference_room', models.BooleanField(default=False)),
                ('Year', models.DateField(null=True)),
            ],
            bases=('property.allproperty',),
        ),
        migrations.CreateModel(
            name='LandProperty',
            fields=[
                ('allproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.allproperty')),
                ('Land_type', models.CharField(choices=[('Farmland', 'Farmland'), ('Playground', 'Playground'), ('warehouse', 'warehouse')], max_length=100, null=True)),
                ('Is_fenced', models.BooleanField(default=False)),
            ],
            bases=('property.allproperty',),
        ),
        migrations.CreateModel(
            name='ResidentialProperty',
            fields=[
                ('allproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.allproperty')),
                ('House_No', models.CharField(max_length=8)),
                ('Floor_count', models.PositiveIntegerField(default=1)),
                ('Bedrooms', models.PositiveIntegerField(default=1)),
                ('Bathrooms', models.PositiveIntegerField(default=1)),
                ('Garage_spaces_Per_Sqft', models.PositiveIntegerField(default=0)),
                ('Has_Pool', models.BooleanField(default=False)),
                ('Has_Garden', models.BooleanField(default=False)),
                ('Number_of_Balcony', models.PositiveIntegerField(default=1)),
                ('Year', models.DateField(null=True)),
            ],
            bases=('property.allproperty',),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('criteria', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
