# Generated by Django 5.0.2 on 2024-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproperty',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
    ]
