# Generated by Django 5.0.2 on 2024-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproperty',
            name='Business_type',
            field=models.CharField(choices=[('office', 'Office'), ('community_Center', 'community_Center'), ('shop', 'Shop'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
