# Generated by Django 5.0.2 on 2025-10-16 19:29

import RealEstate.cloudinary_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_allproperty_needs_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproperty',
            name='Property_Documents',
            field=models.FileField(upload_to=RealEstate.cloudinary_utils.property_documents_upload_to),
        ),
        migrations.AlterField(
            model_name='allproperty',
            name='Property_Pictures',
            field=models.ImageField(upload_to=RealEstate.cloudinary_utils.property_pictures_upload_to),
        ),
    ]
