# Generated by Django 5.0.2 on 2024-03-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_type_allproperty_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialproperty',
            name='year_built',
        ),
    ]
