# Generated by Django 5.0.2 on 2024-03-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproperty',
            name='Approval_by_Agent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
