# Generated by Django 5.0.2 on 2024-03-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
