# Generated by Django 5.0.2 on 2024-03-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_residentialproperty_year_built'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproperty',
            old_name='Description',
            new_name='Property_Description',
        ),
        migrations.RenameField(
            model_name='allproperty',
            old_name='Name',
            new_name='Property_Name',
        ),
        migrations.RenameField(
            model_name='allproperty',
            old_name='Media',
            new_name='Property_Pictures',
        ),
        migrations.RemoveField(
            model_name='allproperty',
            name='Rent',
        ),
        migrations.RemoveField(
            model_name='allproperty',
            name='Sale',
        ),
        migrations.AddField(
            model_name='allproperty',
            name='Property_on',
            field=models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=20, null=True),
        ),
    ]
