# Generated by Django 5.0.2 on 2024-03-22 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproperty',
            name='District',
        ),
        migrations.AddField(
            model_name='allproperty',
            name='Approval_by_Agent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='allproperty',
            name='Area',
            field=models.CharField(choices=[('Gulshan', 'Gulshan'), ('Banani', 'Banani'), ('Dhanmondi', 'Dhanmondi'), ('Bashundhara R/A', 'Bashundhara R/A')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allproperty',
            name='City',
            field=models.CharField(choices=[('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='allproperty',
            name='Property_on',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('criteria', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
