# Generated by Django 5.0.2 on 2024-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_rename_description_allproperty_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialproperty',
            name='year_built',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='year_built',
            field=models.DateField(blank=True, null=True),
        ),
    ]
