# Generated by Django 5.0.2 on 2024-03-20 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_delete_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproperty',
            name='District',
        ),
        migrations.AddField(
            model_name='allproperty',
            name='Area',
            field=models.CharField(choices=[('Gulshan', 'Gulshan'), ('Banani', 'Banani'), ('Dhanmondi', 'Dhanmondi'), ('Bashundhara R/A', 'Bashundhara R/A')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allproperty',
            name='City',
            field=models.CharField(choices=[('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='allproperty',
            name='Property_on',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=20, null=True),
        ),
    ]
