# Generated by Django 5.0.2 on 2024-03-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_allproperty_approval_by_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproperty',
            name='Approval_by_Agent',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
