# Generated by Django 5.0.2 on 2024-03-01 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_profile_picture_and_more'),
        ('property', '0005_residentialproperty_year_built_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproperty',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='authentication.userprofile'),
        ),
    ]
