# Generated by Django 5.0.2 on 2024-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_allproperty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproperty',
            name='Property_Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
