# Generated by Django 5.0.2 on 2024-03-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_allproperty_property_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproperty',
            name='Year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='Year',
            field=models.DateField(null=True),
        ),
    ]
