# Generated by Django 5.0.2 on 2024-03-30 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_commercialproperty_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproperty',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allproperty',
            name='soldDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
