# Generated by Django 5.0.2 on 2024-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('property_name', models.CharField(max_length=233)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.IntegerField()),
            ],
        ),
    ]
