# Generated by Django 5.0.2 on 2024-04-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
        ('auction', '0006_merge_20240415_2030'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auc_property'),
        ),
    ]
