# Generated by Django 5.0.2 on 2025-10-16 19:29

import RealEstate.cloudinary_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=RealEstate.cloudinary_utils.profile_picture_upload_to),
        ),
    ]
