# Generated by Django 5.0.2 on 2024-04-02 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auc_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Name', models.CharField(max_length=200)),
                ('Total_area_in_sqft', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('Property_Pictures', models.ImageField(upload_to='pics')),
                ('Road_No', models.CharField(max_length=4)),
                ('Block', models.CharField(max_length=10)),
                ('City', models.CharField(choices=[('Dhaka', 'Dhaka')], max_length=100)),
                ('Postal_code', models.CharField(max_length=4)),
                ('Area', models.CharField(choices=[('Gulshan', 'Gulshan'), ('Banani', 'Banani'), ('Dhanmondi', 'Dhanmondi'), ('Bashundhara R/A', 'Bashundhara R/A')], max_length=100)),
                ('Property_type', models.CharField(choices=[('commercial', 'Commercial'), ('land', 'Land'), ('residential', 'Residential')], max_length=20)),
                ('Property_Documents', models.FileField(upload_to='property_documents')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='authentication.userprofile')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Auc_CommercialProperty',
            fields=[
                ('auc_property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auction.auc_property')),
                ('House_No', models.CharField(max_length=8)),
                ('Business_type', models.CharField(choices=[('office', 'Office'), ('community_Center', 'community_Center'), ('shop', 'Shop'), ('other', 'Other')], max_length=20, null=True)),
                ('Parking_spaces', models.PositiveIntegerField(default=0)),
                ('Has_elevator', models.BooleanField(default=False)),
                ('Has_security_system', models.BooleanField(default=False)),
                ('Has_conference_room', models.BooleanField(default=False)),
                ('Year', models.DateField(null=True)),
            ],
            bases=('auction.auc_property',),
        ),
        migrations.CreateModel(
            name='Auc_LandProperty',
            fields=[
                ('auc_property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auction.auc_property')),
                ('Land_type', models.CharField(choices=[('Farmland', 'Farmland'), ('Playground', 'Playground'), ('warehouse', 'warehouse')], max_length=100, null=True)),
                ('Is_fenced', models.BooleanField(default=False)),
            ],
            bases=('auction.auc_property',),
        ),
        migrations.CreateModel(
            name='Auc_ResidentialProperty',
            fields=[
                ('auc_property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auction.auc_property')),
                ('House_No', models.CharField(max_length=8)),
                ('Floor_count', models.PositiveIntegerField(default=1)),
                ('Bedrooms', models.PositiveIntegerField(default=1)),
                ('Bathrooms', models.PositiveIntegerField(default=1)),
                ('Garage_spaces_Per_Sqft', models.PositiveIntegerField(default=0)),
                ('Has_Pool', models.BooleanField(default=False)),
                ('Has_Garden', models.BooleanField(default=False)),
                ('Number_of_Balcony', models.PositiveIntegerField(default=1)),
                ('Year', models.DateField(null=True)),
            ],
            bases=('auction.auc_property',),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auc_property')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
