# Generated by Django 5.0.2 on 2024-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auc_property',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
