# Generated by Django 5.0.2 on 2024-03-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auc_property',
            name='Approval_by_Agent',
        ),
    ]
