# Generated by Django 5.0.2 on 2024-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auc_property',
            name='Approval_by_Agent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auc_property',
            name='current_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auc_property',
            name='start_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
