# Generated by Django 5.0.2 on 2024-03-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_auc_property_approval_by_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auc_property',
            name='Property_on',
        ),
    ]
