# Generated by Django 5.0.2 on 2024-04-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_auc_property_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auc_property',
            name='current_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
