# Generated by Django 5.0.2 on 2024-04-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auc_property_property_documents_and_more'),
        ('auction', '0005_alter_auc_property_current_price'),
    ]

    operations = [
    ]
