# Generated by Django 5.0.2 on 2024-03-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_auc_property_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auc_property',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
