# Generated by Django 5.0.2 on 2025-10-16 19:29

import RealEstate.cloudinary_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_auc_property_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auc_property',
            name='Property_Documents',
            field=models.FileField(blank=True, null=True, upload_to=RealEstate.cloudinary_utils.auction_documents_upload_to),
        ),
        migrations.AlterField(
            model_name='auc_property',
            name='Property_Pictures',
            field=models.ImageField(default=None, upload_to=RealEstate.cloudinary_utils.auction_pictures_upload_to),
        ),
    ]
